apiVersion: v1
kind: Service

metadata:
  name: {{.Values.redis.name}}
  labels:
    app: {{.Values.redis.name}}

spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: api

  selector:
    app: {{.Values.redis.name}}