appserver:
  name: app-server
  replicas: 3

  image:
    name: app-server
    tag: v2
    port: 3000

  env:
    NODE_ENV: production

  service:
    name: app-server-service
    type: ClusterIP

userservice:
  name: user-service
  replicas: 2

  image:
    name: user-service
    tag: latest
    port: 4000

  env:
    NODE_ENV: production

  service:
    name: user-service-service
    type: ClusterIP

nginx:
  name: app-nginx
  replicas: 1

  image:
    name: app-nginx
    tag: latest
    port: 80

  service:
    name: app-nginx-service
    type: LoadBalancer

redis:
  name: redis

mongodb:
  name: mongodb

  user:
    name: YWRtaW4=
    backup: dXNlcm5hbWU=
    password: cGFzc3dvcmQ=

  image:
    name: mongo
    tag: 3.6

  service:
    name: mongodb-service

